# Generated by Django 3.0.2 on 2020-02-05 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='cleaner',
            fields=[
                ('cleaner_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.City')),
            ],
        ),
    ]
