# Generated by Django 3.0.2 on 2020-02-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_cleaner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaner',
            old_name='cleaner_id',
            new_name='user_id',
        ),
    ]
