# Generated by Django 3.0.2 on 2020-02-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200205_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
