# Generated by Django 3.0.2 on 2020-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='quality_score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
