# Generated by Django 3.0.2 on 2020-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_cleaner_quality_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
